// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/system/v1/announcement.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnouncementInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 公告标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 公告内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 公告类型（1通知 2公告）
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 状态 0 未发布 1 已发布
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 发布者ID
	PublisherId int64 `protobuf:"varint,7,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	// 发布者名称
	PublisherName string `protobuf:"bytes,8,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	// 发布时间
	PublishTime int64 `protobuf:"varint,9,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     int64 `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementInfo) Reset() {
	*x = AnnouncementInfo{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementInfo) ProtoMessage() {}

func (x *AnnouncementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementInfo.ProtoReflect.Descriptor instead.
func (*AnnouncementInfo) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{0}
}

func (x *AnnouncementInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnnouncementInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnnouncementInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AnnouncementInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AnnouncementInfo) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *AnnouncementInfo) GetPublisherId() int64 {
	if x != nil {
		return x.PublisherId
	}
	return 0
}

func (x *AnnouncementInfo) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *AnnouncementInfo) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *AnnouncementInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AnnouncementInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建公告请求
type CreateAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告标题
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 公告内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 公告类型
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// 状态 0 未发布 1 已发布
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 发布时间
	PublishTime   int64 `protobuf:"varint,6,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnouncementRequest) Reset() {
	*x = CreateAnnouncementRequest{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementRequest) ProtoMessage() {}

func (x *CreateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnnouncementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateAnnouncementRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAnnouncementRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

// 创建公告响应
type CreateAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnouncementReply) Reset() {
	*x = CreateAnnouncementReply{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementReply) ProtoMessage() {}

func (x *CreateAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementReply.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{2}
}

// 更新公告请求
type UpdateAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 公告标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 公告内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 公告类型
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 状态 0 未发布 1 已发布
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 发布时间
	PublishTime   int64 `protobuf:"varint,7,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementRequest) Reset() {
	*x = UpdateAnnouncementRequest{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementRequest) ProtoMessage() {}

func (x *UpdateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAnnouncementRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAnnouncementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateAnnouncementRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAnnouncementRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *UpdateAnnouncementRequest) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

// 更新公告响应
type UpdateAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementReply) Reset() {
	*x = UpdateAnnouncementReply{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementReply) ProtoMessage() {}

func (x *UpdateAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementReply.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{4}
}

// 删除公告请求
type DeleteAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnouncementRequest) Reset() {
	*x = DeleteAnnouncementRequest{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementRequest) ProtoMessage() {}

func (x *DeleteAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAnnouncementRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除公告响应
type DeleteAnnouncementReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnouncementReply) Reset() {
	*x = DeleteAnnouncementReply{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementReply) ProtoMessage() {}

func (x *DeleteAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementReply.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{6}
}

// 获取公告请求
type GetAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnnouncementRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取公告响应
type GetAnnouncementReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告信息
	Announcement  *AnnouncementInfo `protobuf:"bytes,1,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementReply) Reset() {
	*x = GetAnnouncementReply{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementReply) ProtoMessage() {}

func (x *GetAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementReply.ProtoReflect.Descriptor instead.
func (*GetAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnnouncementReply) GetAnnouncement() *AnnouncementInfo {
	if x != nil {
		return x.Announcement
	}
	return nil
}

// 公告列表请求
type ListAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每页数量
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 页码
	Current int32 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	// 公告标题，用于筛选
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// 公告类型，用于筛选
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 状态，用于筛选 0 未发布 1 已发布
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 开始时间
	BeginTime int64 `protobuf:"varint,6,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	// 结束时间
	EndTime       int64 `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementRequest) Reset() {
	*x = ListAnnouncementRequest{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementRequest) ProtoMessage() {}

func (x *ListAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{9}
}

func (x *ListAnnouncementRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAnnouncementRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListAnnouncementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAnnouncementRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListAnnouncementRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListAnnouncementRequest) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *ListAnnouncementRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 公告列表响应
type ListAnnouncementReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告列表
	Items []*AnnouncementInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementReply) Reset() {
	*x = ListAnnouncementReply{}
	mi := &file_api_system_v1_announcement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementReply) ProtoMessage() {}

func (x *ListAnnouncementReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_announcement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementReply.ProtoReflect.Descriptor instead.
func (*ListAnnouncementReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_announcement_proto_rawDescGZIP(), []int{10}
}

func (x *ListAnnouncementReply) GetItems() []*AnnouncementInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAnnouncementReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_system_v1_announcement_proto protoreflect.FileDescriptor

const file_api_system_v1_announcement_proto_rawDesc = "" +
	"\n" +
	" api/system/v1/announcement.proto\x12\rapi.system.v1\x1a\x1cgoogle/api/annotations.proto\"\xd1\x02\n" +
	"\x10AnnouncementInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\x06remark\x18\x06 \x01(\tH\x00R\x06remark\x88\x01\x01\x12!\n" +
	"\fpublisher_id\x18\a \x01(\x03R\vpublisherId\x12%\n" +
	"\x0epublisher_name\x18\b \x01(\tR\rpublisherName\x12!\n" +
	"\fpublish_time\x18\t \x01(\x03R\vpublishTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAtB\t\n" +
	"\a_remark\"\xc2\x01\n" +
	"\x19CreateAnnouncementRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1b\n" +
	"\x06remark\x18\x05 \x01(\tH\x00R\x06remark\x88\x01\x01\x12!\n" +
	"\fpublish_time\x18\x06 \x01(\x03R\vpublishTimeB\t\n" +
	"\a_remark\"\x19\n" +
	"\x17CreateAnnouncementReply\"\xd2\x01\n" +
	"\x19UpdateAnnouncementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\x06remark\x18\x06 \x01(\tH\x00R\x06remark\x88\x01\x01\x12!\n" +
	"\fpublish_time\x18\a \x01(\x03R\vpublishTimeB\t\n" +
	"\a_remark\"\x19\n" +
	"\x17UpdateAnnouncementReply\"+\n" +
	"\x19DeleteAnnouncementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\x17DeleteAnnouncementReply\"(\n" +
	"\x16GetAnnouncementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"[\n" +
	"\x14GetAnnouncementReply\x12C\n" +
	"\fannouncement\x18\x01 \x01(\v2\x1f.api.system.v1.AnnouncementInfoR\fannouncement\"\xcc\x01\n" +
	"\x17ListAnnouncementRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x06 \x01(\x03R\tbeginTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\"d\n" +
	"\x15ListAnnouncementReply\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.api.system.v1.AnnouncementInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xe5\x05\n" +
	"\fAnnouncement\x12\x8e\x01\n" +
	"\x12CreateAnnouncement\x12(.api.system.v1.CreateAnnouncementRequest\x1a&.api.system.v1.CreateAnnouncementReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/system/announcement\x12\x95\x01\n" +
	"\x12UpdateAnnouncement\x12(.api.system.v1.UpdateAnnouncementRequest\x1a&.api.system.v1.UpdateAnnouncementReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/system/announcement/update\x12\x95\x01\n" +
	"\x12DeleteAnnouncement\x12(.api.system.v1.DeleteAnnouncementRequest\x1a&.api.system.v1.DeleteAnnouncementReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/system/announcement/delete\x12\x86\x01\n" +
	"\x0fGetAnnouncement\x12%.api.system.v1.GetAnnouncementRequest\x1a#.api.system.v1.GetAnnouncementReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/system/announcement/get\x12\x8a\x01\n" +
	"\x10ListAnnouncement\x12&.api.system.v1.ListAnnouncementRequest\x1a$.api.system.v1.ListAnnouncementReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/system/announcement/listB4\n" +
	"\rapi.system.v1P\x01Z!spark/api/system/v1;v1b\x06proto3"

var (
	file_api_system_v1_announcement_proto_rawDescOnce sync.Once
	file_api_system_v1_announcement_proto_rawDescData []byte
)

func file_api_system_v1_announcement_proto_rawDescGZIP() []byte {
	file_api_system_v1_announcement_proto_rawDescOnce.Do(func() {
		file_api_system_v1_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1_announcement_proto_rawDesc), len(file_api_system_v1_announcement_proto_rawDesc)))
	})
	return file_api_system_v1_announcement_proto_rawDescData
}

var file_api_system_v1_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_system_v1_announcement_proto_goTypes = []any{
	(*AnnouncementInfo)(nil),          // 0: api.system.v1.AnnouncementInfo
	(*CreateAnnouncementRequest)(nil), // 1: api.system.v1.CreateAnnouncementRequest
	(*CreateAnnouncementReply)(nil),   // 2: api.system.v1.CreateAnnouncementReply
	(*UpdateAnnouncementRequest)(nil), // 3: api.system.v1.UpdateAnnouncementRequest
	(*UpdateAnnouncementReply)(nil),   // 4: api.system.v1.UpdateAnnouncementReply
	(*DeleteAnnouncementRequest)(nil), // 5: api.system.v1.DeleteAnnouncementRequest
	(*DeleteAnnouncementReply)(nil),   // 6: api.system.v1.DeleteAnnouncementReply
	(*GetAnnouncementRequest)(nil),    // 7: api.system.v1.GetAnnouncementRequest
	(*GetAnnouncementReply)(nil),      // 8: api.system.v1.GetAnnouncementReply
	(*ListAnnouncementRequest)(nil),   // 9: api.system.v1.ListAnnouncementRequest
	(*ListAnnouncementReply)(nil),     // 10: api.system.v1.ListAnnouncementReply
}
var file_api_system_v1_announcement_proto_depIdxs = []int32{
	0,  // 0: api.system.v1.GetAnnouncementReply.announcement:type_name -> api.system.v1.AnnouncementInfo
	0,  // 1: api.system.v1.ListAnnouncementReply.items:type_name -> api.system.v1.AnnouncementInfo
	1,  // 2: api.system.v1.Announcement.CreateAnnouncement:input_type -> api.system.v1.CreateAnnouncementRequest
	3,  // 3: api.system.v1.Announcement.UpdateAnnouncement:input_type -> api.system.v1.UpdateAnnouncementRequest
	5,  // 4: api.system.v1.Announcement.DeleteAnnouncement:input_type -> api.system.v1.DeleteAnnouncementRequest
	7,  // 5: api.system.v1.Announcement.GetAnnouncement:input_type -> api.system.v1.GetAnnouncementRequest
	9,  // 6: api.system.v1.Announcement.ListAnnouncement:input_type -> api.system.v1.ListAnnouncementRequest
	2,  // 7: api.system.v1.Announcement.CreateAnnouncement:output_type -> api.system.v1.CreateAnnouncementReply
	4,  // 8: api.system.v1.Announcement.UpdateAnnouncement:output_type -> api.system.v1.UpdateAnnouncementReply
	6,  // 9: api.system.v1.Announcement.DeleteAnnouncement:output_type -> api.system.v1.DeleteAnnouncementReply
	8,  // 10: api.system.v1.Announcement.GetAnnouncement:output_type -> api.system.v1.GetAnnouncementReply
	10, // 11: api.system.v1.Announcement.ListAnnouncement:output_type -> api.system.v1.ListAnnouncementReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_system_v1_announcement_proto_init() }
func file_api_system_v1_announcement_proto_init() {
	if File_api_system_v1_announcement_proto != nil {
		return
	}
	file_api_system_v1_announcement_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_system_v1_announcement_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_system_v1_announcement_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1_announcement_proto_rawDesc), len(file_api_system_v1_announcement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_v1_announcement_proto_goTypes,
		DependencyIndexes: file_api_system_v1_announcement_proto_depIdxs,
		MessageInfos:      file_api_system_v1_announcement_proto_msgTypes,
	}.Build()
	File_api_system_v1_announcement_proto = out.File
	file_api_system_v1_announcement_proto_goTypes = nil
	file_api_system_v1_announcement_proto_depIdxs = nil
}
