// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/system/v1/file.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenFileUploadUrlRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenFileUploadUrlRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenFileUploadUrlRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenFileUploadUrlRequestMultiError, or nil if none found.
func (m *GenFileUploadUrlRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenFileUploadUrlRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetFileName()) < 1 {
		err := GenFileUploadUrlRequestValidationError{
			field:  "FileName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetFileSize() <= 0 {
		err := GenFileUploadUrlRequestValidationError{
			field:  "FileSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for MimeType

	if _, ok := _GenFileUploadUrlRequest_BizType_InLookup[m.GetBizType()]; !ok {
		err := GenFileUploadUrlRequestValidationError{
			field:  "BizType",
			reason: "value must be in list [1 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for UsageType

	// no validation rules for ForceSts

	if m.Callback != nil {

		if all {
			switch v := interface{}(m.GetCallback()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GenFileUploadUrlRequestValidationError{
						field:  "Callback",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GenFileUploadUrlRequestValidationError{
						field:  "Callback",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCallback()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GenFileUploadUrlRequestValidationError{
					field:  "Callback",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GenFileUploadUrlRequestMultiError(errors)
	}

	return nil
}

// GenFileUploadUrlRequestMultiError is an error wrapping multiple validation
// errors returned by GenFileUploadUrlRequest.ValidateAll() if the designated
// constraints aren't met.
type GenFileUploadUrlRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenFileUploadUrlRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenFileUploadUrlRequestMultiError) AllErrors() []error { return m }

// GenFileUploadUrlRequestValidationError is the validation error returned by
// GenFileUploadUrlRequest.Validate if the designated constraints aren't met.
type GenFileUploadUrlRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenFileUploadUrlRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenFileUploadUrlRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenFileUploadUrlRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenFileUploadUrlRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenFileUploadUrlRequestValidationError) ErrorName() string {
	return "GenFileUploadUrlRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenFileUploadUrlRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenFileUploadUrlRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenFileUploadUrlRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenFileUploadUrlRequestValidationError{}

var _GenFileUploadUrlRequest_BizType_InLookup = map[int32]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on GenFileUploadUrlReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenFileUploadUrlReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenFileUploadUrlReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenFileUploadUrlReplyMultiError, or nil if none found.
func (m *GenFileUploadUrlReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GenFileUploadUrlReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Sts != nil {

		if all {
			switch v := interface{}(m.GetSts()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GenFileUploadUrlReplyValidationError{
						field:  "Sts",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GenFileUploadUrlReplyValidationError{
						field:  "Sts",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSts()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GenFileUploadUrlReplyValidationError{
					field:  "Sts",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Url != nil {

		if all {
			switch v := interface{}(m.GetUrl()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GenFileUploadUrlReplyValidationError{
						field:  "Url",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GenFileUploadUrlReplyValidationError{
						field:  "Url",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUrl()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GenFileUploadUrlReplyValidationError{
					field:  "Url",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GenFileUploadUrlReplyMultiError(errors)
	}

	return nil
}

// GenFileUploadUrlReplyMultiError is an error wrapping multiple validation
// errors returned by GenFileUploadUrlReply.ValidateAll() if the designated
// constraints aren't met.
type GenFileUploadUrlReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenFileUploadUrlReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenFileUploadUrlReplyMultiError) AllErrors() []error { return m }

// GenFileUploadUrlReplyValidationError is the validation error returned by
// GenFileUploadUrlReply.Validate if the designated constraints aren't met.
type GenFileUploadUrlReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenFileUploadUrlReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenFileUploadUrlReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenFileUploadUrlReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenFileUploadUrlReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenFileUploadUrlReplyValidationError) ErrorName() string {
	return "GenFileUploadUrlReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GenFileUploadUrlReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenFileUploadUrlReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenFileUploadUrlReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenFileUploadUrlReplyValidationError{}

// Validate checks the field values on FileUploadCallbackRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FileUploadCallbackRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileUploadCallbackRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FileUploadCallbackRequestMultiError, or nil if none found.
func (m *FileUploadCallbackRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FileUploadCallbackRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Bucket

	// no validation rules for Object

	// no validation rules for Etag

	// no validation rules for Size

	// no validation rules for MimeType

	// no validation rules for CustomVars

	if m.ImageInfo != nil {

		if all {
			switch v := interface{}(m.GetImageInfo()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FileUploadCallbackRequestValidationError{
						field:  "ImageInfo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FileUploadCallbackRequestValidationError{
						field:  "ImageInfo",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetImageInfo()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FileUploadCallbackRequestValidationError{
					field:  "ImageInfo",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FileUploadCallbackRequestMultiError(errors)
	}

	return nil
}

// FileUploadCallbackRequestMultiError is an error wrapping multiple validation
// errors returned by FileUploadCallbackRequest.ValidateAll() if the
// designated constraints aren't met.
type FileUploadCallbackRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileUploadCallbackRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileUploadCallbackRequestMultiError) AllErrors() []error { return m }

// FileUploadCallbackRequestValidationError is the validation error returned by
// FileUploadCallbackRequest.Validate if the designated constraints aren't met.
type FileUploadCallbackRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileUploadCallbackRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileUploadCallbackRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileUploadCallbackRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileUploadCallbackRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileUploadCallbackRequestValidationError) ErrorName() string {
	return "FileUploadCallbackRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FileUploadCallbackRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileUploadCallbackRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileUploadCallbackRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileUploadCallbackRequestValidationError{}

// Validate checks the field values on FileUploadCallbackReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FileUploadCallbackReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileUploadCallbackReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FileUploadCallbackReplyMultiError, or nil if none found.
func (m *FileUploadCallbackReply) ValidateAll() error {
	return m.validate(true)
}

func (m *FileUploadCallbackReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if m.FileUrl != nil {
		// no validation rules for FileUrl
	}

	if len(errors) > 0 {
		return FileUploadCallbackReplyMultiError(errors)
	}

	return nil
}

// FileUploadCallbackReplyMultiError is an error wrapping multiple validation
// errors returned by FileUploadCallbackReply.ValidateAll() if the designated
// constraints aren't met.
type FileUploadCallbackReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileUploadCallbackReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileUploadCallbackReplyMultiError) AllErrors() []error { return m }

// FileUploadCallbackReplyValidationError is the validation error returned by
// FileUploadCallbackReply.Validate if the designated constraints aren't met.
type FileUploadCallbackReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileUploadCallbackReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileUploadCallbackReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileUploadCallbackReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileUploadCallbackReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileUploadCallbackReplyValidationError) ErrorName() string {
	return "FileUploadCallbackReplyValidationError"
}

// Error satisfies the builtin error interface
func (e FileUploadCallbackReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileUploadCallbackReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileUploadCallbackReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileUploadCallbackReplyValidationError{}

// Validate checks the field values on GenFileUploadUrlRequest_Callback with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GenFileUploadUrlRequest_Callback) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenFileUploadUrlRequest_Callback with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GenFileUploadUrlRequest_CallbackMultiError, or nil if none found.
func (m *GenFileUploadUrlRequest_Callback) ValidateAll() error {
	return m.validate(true)
}

func (m *GenFileUploadUrlRequest_Callback) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enable

	// no validation rules for Url

	// no validation rules for Body

	if len(errors) > 0 {
		return GenFileUploadUrlRequest_CallbackMultiError(errors)
	}

	return nil
}

// GenFileUploadUrlRequest_CallbackMultiError is an error wrapping multiple
// validation errors returned by
// GenFileUploadUrlRequest_Callback.ValidateAll() if the designated
// constraints aren't met.
type GenFileUploadUrlRequest_CallbackMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenFileUploadUrlRequest_CallbackMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenFileUploadUrlRequest_CallbackMultiError) AllErrors() []error { return m }

// GenFileUploadUrlRequest_CallbackValidationError is the validation error
// returned by GenFileUploadUrlRequest_Callback.Validate if the designated
// constraints aren't met.
type GenFileUploadUrlRequest_CallbackValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenFileUploadUrlRequest_CallbackValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenFileUploadUrlRequest_CallbackValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenFileUploadUrlRequest_CallbackValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenFileUploadUrlRequest_CallbackValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenFileUploadUrlRequest_CallbackValidationError) ErrorName() string {
	return "GenFileUploadUrlRequest_CallbackValidationError"
}

// Error satisfies the builtin error interface
func (e GenFileUploadUrlRequest_CallbackValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenFileUploadUrlRequest_Callback.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenFileUploadUrlRequest_CallbackValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenFileUploadUrlRequest_CallbackValidationError{}

// Validate checks the field values on GenFileUploadUrlReply_Sts with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenFileUploadUrlReply_Sts) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenFileUploadUrlReply_Sts with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenFileUploadUrlReply_StsMultiError, or nil if none found.
func (m *GenFileUploadUrlReply_Sts) ValidateAll() error {
	return m.validate(true)
}

func (m *GenFileUploadUrlReply_Sts) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessKeyId

	// no validation rules for AccessKeySecret

	// no validation rules for SecurityToken

	// no validation rules for Region

	// no validation rules for BucketName

	// no validation rules for Expiration

	// no validation rules for ObjectName

	// no validation rules for Endpoint

	if len(errors) > 0 {
		return GenFileUploadUrlReply_StsMultiError(errors)
	}

	return nil
}

// GenFileUploadUrlReply_StsMultiError is an error wrapping multiple validation
// errors returned by GenFileUploadUrlReply_Sts.ValidateAll() if the
// designated constraints aren't met.
type GenFileUploadUrlReply_StsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenFileUploadUrlReply_StsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenFileUploadUrlReply_StsMultiError) AllErrors() []error { return m }

// GenFileUploadUrlReply_StsValidationError is the validation error returned by
// GenFileUploadUrlReply_Sts.Validate if the designated constraints aren't met.
type GenFileUploadUrlReply_StsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenFileUploadUrlReply_StsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenFileUploadUrlReply_StsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenFileUploadUrlReply_StsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenFileUploadUrlReply_StsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenFileUploadUrlReply_StsValidationError) ErrorName() string {
	return "GenFileUploadUrlReply_StsValidationError"
}

// Error satisfies the builtin error interface
func (e GenFileUploadUrlReply_StsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenFileUploadUrlReply_Sts.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenFileUploadUrlReply_StsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenFileUploadUrlReply_StsValidationError{}

// Validate checks the field values on GenFileUploadUrlReply_Url with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenFileUploadUrlReply_Url) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenFileUploadUrlReply_Url with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenFileUploadUrlReply_UrlMultiError, or nil if none found.
func (m *GenFileUploadUrlReply_Url) ValidateAll() error {
	return m.validate(true)
}

func (m *GenFileUploadUrlReply_Url) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Method

	// no validation rules for Expiration

	// no validation rules for SignedHeaders

	if len(errors) > 0 {
		return GenFileUploadUrlReply_UrlMultiError(errors)
	}

	return nil
}

// GenFileUploadUrlReply_UrlMultiError is an error wrapping multiple validation
// errors returned by GenFileUploadUrlReply_Url.ValidateAll() if the
// designated constraints aren't met.
type GenFileUploadUrlReply_UrlMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenFileUploadUrlReply_UrlMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenFileUploadUrlReply_UrlMultiError) AllErrors() []error { return m }

// GenFileUploadUrlReply_UrlValidationError is the validation error returned by
// GenFileUploadUrlReply_Url.Validate if the designated constraints aren't met.
type GenFileUploadUrlReply_UrlValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenFileUploadUrlReply_UrlValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenFileUploadUrlReply_UrlValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenFileUploadUrlReply_UrlValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenFileUploadUrlReply_UrlValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenFileUploadUrlReply_UrlValidationError) ErrorName() string {
	return "GenFileUploadUrlReply_UrlValidationError"
}

// Error satisfies the builtin error interface
func (e GenFileUploadUrlReply_UrlValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenFileUploadUrlReply_Url.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenFileUploadUrlReply_UrlValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenFileUploadUrlReply_UrlValidationError{}

// Validate checks the field values on FileUploadCallbackRequest_ImageInfo with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *FileUploadCallbackRequest_ImageInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileUploadCallbackRequest_ImageInfo
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// FileUploadCallbackRequest_ImageInfoMultiError, or nil if none found.
func (m *FileUploadCallbackRequest_ImageInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *FileUploadCallbackRequest_ImageInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	// no validation rules for Width

	// no validation rules for Format

	if len(errors) > 0 {
		return FileUploadCallbackRequest_ImageInfoMultiError(errors)
	}

	return nil
}

// FileUploadCallbackRequest_ImageInfoMultiError is an error wrapping multiple
// validation errors returned by
// FileUploadCallbackRequest_ImageInfo.ValidateAll() if the designated
// constraints aren't met.
type FileUploadCallbackRequest_ImageInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileUploadCallbackRequest_ImageInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileUploadCallbackRequest_ImageInfoMultiError) AllErrors() []error { return m }

// FileUploadCallbackRequest_ImageInfoValidationError is the validation error
// returned by FileUploadCallbackRequest_ImageInfo.Validate if the designated
// constraints aren't met.
type FileUploadCallbackRequest_ImageInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileUploadCallbackRequest_ImageInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileUploadCallbackRequest_ImageInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileUploadCallbackRequest_ImageInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileUploadCallbackRequest_ImageInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileUploadCallbackRequest_ImageInfoValidationError) ErrorName() string {
	return "FileUploadCallbackRequest_ImageInfoValidationError"
}

// Error satisfies the builtin error interface
func (e FileUploadCallbackRequest_ImageInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileUploadCallbackRequest_ImageInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileUploadCallbackRequest_ImageInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileUploadCallbackRequest_ImageInfoValidationError{}
