// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/system/v1/file.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成文件上传URL的请求
type GenFileUploadUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件名
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// 文件大小（字节数）
	FileSize int64 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// MIME类型(如image/jpeg)
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// 桶权限类型(1=公开桶/2=私有桶)
	BizType int32 `protobuf:"varint,4,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	// 业务用途(如avatar/contract/product_img,可选)
	UsageType string `protobuf:"bytes,5,opt,name=usage_type,json=usageType,proto3" json:"usage_type,omitempty"`
	// 强制使用STS方式上传
	ForceSts bool `protobuf:"varint,6,opt,name=force_sts,json=forceSts,proto3" json:"force_sts,omitempty"`
	// 回调配置，如果设置会覆盖全局配置
	Callback      *GenFileUploadUrlRequest_Callback `protobuf:"bytes,7,opt,name=callback,proto3,oneof" json:"callback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenFileUploadUrlRequest) Reset() {
	*x = GenFileUploadUrlRequest{}
	mi := &file_api_system_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenFileUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenFileUploadUrlRequest) ProtoMessage() {}

func (x *GenFileUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenFileUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GenFileUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *GenFileUploadUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GenFileUploadUrlRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GenFileUploadUrlRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenFileUploadUrlRequest) GetBizType() int32 {
	if x != nil {
		return x.BizType
	}
	return 0
}

func (x *GenFileUploadUrlRequest) GetUsageType() string {
	if x != nil {
		return x.UsageType
	}
	return ""
}

func (x *GenFileUploadUrlRequest) GetForceSts() bool {
	if x != nil {
		return x.ForceSts
	}
	return false
}

func (x *GenFileUploadUrlRequest) GetCallback() *GenFileUploadUrlRequest_Callback {
	if x != nil {
		return x.Callback
	}
	return nil
}

// 生成文件上传URL的响应
type GenFileUploadUrlReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sts           *GenFileUploadUrlReply_Sts `protobuf:"bytes,1,opt,name=sts,proto3,oneof" json:"sts,omitempty"`
	Url           *GenFileUploadUrlReply_Url `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenFileUploadUrlReply) Reset() {
	*x = GenFileUploadUrlReply{}
	mi := &file_api_system_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenFileUploadUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenFileUploadUrlReply) ProtoMessage() {}

func (x *GenFileUploadUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenFileUploadUrlReply.ProtoReflect.Descriptor instead.
func (*GenFileUploadUrlReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *GenFileUploadUrlReply) GetSts() *GenFileUploadUrlReply_Sts {
	if x != nil {
		return x.Sts
	}
	return nil
}

func (x *GenFileUploadUrlReply) GetUrl() *GenFileUploadUrlReply_Url {
	if x != nil {
		return x.Url
	}
	return nil
}

// 文件上传完成回调请求
type FileUploadCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 存储桶名称
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// 文件对象名称(key)
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// 文件ETag
	Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	// 文件大小(字节)
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// 文件MIME类型
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// 图片信息
	ImageInfo *FileUploadCallbackRequest_ImageInfo `protobuf:"bytes,6,opt,name=image_info,json=imageInfo,proto3,oneof" json:"image_info,omitempty"`
	// 自定义变量
	CustomVars    map[string]string `protobuf:"bytes,7,rep,name=custom_vars,json=customVars,proto3" json:"custom_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadCallbackRequest) Reset() {
	*x = FileUploadCallbackRequest{}
	mi := &file_api_system_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCallbackRequest) ProtoMessage() {}

func (x *FileUploadCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCallbackRequest.ProtoReflect.Descriptor instead.
func (*FileUploadCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileUploadCallbackRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileUploadCallbackRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *FileUploadCallbackRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileUploadCallbackRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadCallbackRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileUploadCallbackRequest) GetImageInfo() *FileUploadCallbackRequest_ImageInfo {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

func (x *FileUploadCallbackRequest) GetCustomVars() map[string]string {
	if x != nil {
		return x.CustomVars
	}
	return nil
}

// 文件上传完成回调响应
type FileUploadCallbackReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 处理状态码，0表示成功
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 处理状态信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 文件访问URL
	FileUrl       *string `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3,oneof" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadCallbackReply) Reset() {
	*x = FileUploadCallbackReply{}
	mi := &file_api_system_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadCallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCallbackReply) ProtoMessage() {}

func (x *FileUploadCallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCallbackReply.ProtoReflect.Descriptor instead.
func (*FileUploadCallbackReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *FileUploadCallbackReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileUploadCallbackReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileUploadCallbackReply) GetFileUrl() string {
	if x != nil && x.FileUrl != nil {
		return *x.FileUrl
	}
	return ""
}

// 回调相关参数
type GenFileUploadUrlRequest_Callback struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否启用回调
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	// 回调URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// 回调请求体，支持变量替换: $(key), $(bucket), $(etag), $(size),
	// $(mimeType), $(imageInfo)等
	Body          string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenFileUploadUrlRequest_Callback) Reset() {
	*x = GenFileUploadUrlRequest_Callback{}
	mi := &file_api_system_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenFileUploadUrlRequest_Callback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenFileUploadUrlRequest_Callback) ProtoMessage() {}

func (x *GenFileUploadUrlRequest_Callback) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenFileUploadUrlRequest_Callback.ProtoReflect.Descriptor instead.
func (*GenFileUploadUrlRequest_Callback) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GenFileUploadUrlRequest_Callback) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *GenFileUploadUrlRequest_Callback) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenFileUploadUrlRequest_Callback) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GenFileUploadUrlReply_Sts struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,2,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	SecurityToken   string                 `protobuf:"bytes,3,opt,name=security_token,json=securityToken,proto3" json:"security_token,omitempty"`
	Region          string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	BucketName      string                 `protobuf:"bytes,5,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Expiration      int64                  `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ObjectName      string                 `protobuf:"bytes,7,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Endpoint        string                 `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenFileUploadUrlReply_Sts) Reset() {
	*x = GenFileUploadUrlReply_Sts{}
	mi := &file_api_system_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenFileUploadUrlReply_Sts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenFileUploadUrlReply_Sts) ProtoMessage() {}

func (x *GenFileUploadUrlReply_Sts) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenFileUploadUrlReply_Sts.ProtoReflect.Descriptor instead.
func (*GenFileUploadUrlReply_Sts) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GenFileUploadUrlReply_Sts) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *GenFileUploadUrlReply_Sts) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *GenFileUploadUrlReply_Sts) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type GenFileUploadUrlReply_Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Expiration    int64                  `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	SignedHeaders map[string]string      `protobuf:"bytes,4,rep,name=signed_headers,json=signedHeaders,proto3" json:"signed_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenFileUploadUrlReply_Url) Reset() {
	*x = GenFileUploadUrlReply_Url{}
	mi := &file_api_system_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenFileUploadUrlReply_Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenFileUploadUrlReply_Url) ProtoMessage() {}

func (x *GenFileUploadUrlReply_Url) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenFileUploadUrlReply_Url.ProtoReflect.Descriptor instead.
func (*GenFileUploadUrlReply_Url) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GenFileUploadUrlReply_Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenFileUploadUrlReply_Url) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GenFileUploadUrlReply_Url) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *GenFileUploadUrlReply_Url) GetSignedHeaders() map[string]string {
	if x != nil {
		return x.SignedHeaders
	}
	return nil
}

// 图片信息(如果是图片)
type FileUploadCallbackRequest_ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadCallbackRequest_ImageInfo) Reset() {
	*x = FileUploadCallbackRequest_ImageInfo{}
	mi := &file_api_system_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadCallbackRequest_ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCallbackRequest_ImageInfo) ProtoMessage() {}

func (x *FileUploadCallbackRequest_ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCallbackRequest_ImageInfo.ProtoReflect.Descriptor instead.
func (*FileUploadCallbackRequest_ImageInfo) Descriptor() ([]byte, []int) {
	return file_api_system_v1_file_proto_rawDescGZIP(), []int{2, 1}
}

func (x *FileUploadCallbackRequest_ImageInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FileUploadCallbackRequest_ImageInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FileUploadCallbackRequest_ImageInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_api_system_v1_file_proto protoreflect.FileDescriptor

const file_api_system_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x18api/system/v1/file.proto\x12\rapi.system.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x8d\x03\n" +
	"\x17GenFileUploadUrlRequest\x12$\n" +
	"\tfile_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bfileName\x12$\n" +
	"\tfile_size\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12$\n" +
	"\bbiz_type\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x040\x010\x02R\abizType\x12\x1d\n" +
	"\n" +
	"usage_type\x18\x05 \x01(\tR\tusageType\x12\x1b\n" +
	"\tforce_sts\x18\x06 \x01(\bR\bforceSts\x12P\n" +
	"\bcallback\x18\a \x01(\v2/.api.system.v1.GenFileUploadUrlRequest.CallbackH\x00R\bcallback\x88\x01\x01\x1aH\n" +
	"\bCallback\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04bodyB\v\n" +
	"\t_callback\"\xb6\x05\n" +
	"\x15GenFileUploadUrlReply\x12?\n" +
	"\x03sts\x18\x01 \x01(\v2(.api.system.v1.GenFileUploadUrlReply.StsH\x00R\x03sts\x88\x01\x01\x12?\n" +
	"\x03url\x18\x02 \x01(\v2(.api.system.v1.GenFileUploadUrlReply.UrlH\x01R\x03url\x88\x01\x01\x1a\x92\x02\n" +
	"\x03Sts\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x02 \x01(\tR\x0faccessKeySecret\x12%\n" +
	"\x0esecurity_token\x18\x03 \x01(\tR\rsecurityToken\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1f\n" +
	"\vbucket_name\x18\x05 \x01(\tR\n" +
	"bucketName\x12\x1e\n" +
	"\n" +
	"expiration\x18\x06 \x01(\x03R\n" +
	"expiration\x12\x1f\n" +
	"\vobject_name\x18\a \x01(\tR\n" +
	"objectName\x12\x1a\n" +
	"\bendpoint\x18\b \x01(\tR\bendpoint\x1a\xf5\x01\n" +
	"\x03Url\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"expiration\x18\x03 \x01(\x03R\n" +
	"expiration\x12b\n" +
	"\x0esigned_headers\x18\x04 \x03(\v2;.api.system.v1.GenFileUploadUrlReply.Url.SignedHeadersEntryR\rsignedHeaders\x1a@\n" +
	"\x12SignedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_stsB\x06\n" +
	"\x04_url\"\xe4\x03\n" +
	"\x19FileUploadCallbackRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12V\n" +
	"\n" +
	"image_info\x18\x06 \x01(\v22.api.system.v1.FileUploadCallbackRequest.ImageInfoH\x00R\timageInfo\x88\x01\x01\x12Y\n" +
	"\vcustom_vars\x18\a \x03(\v28.api.system.v1.FileUploadCallbackRequest.CustomVarsEntryR\n" +
	"customVars\x1a=\n" +
	"\x0fCustomVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\tImageInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06formatB\r\n" +
	"\v_image_info\"t\n" +
	"\x17FileUploadCallbackReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\bfile_url\x18\x03 \x01(\tH\x00R\afileUrl\x88\x01\x01B\v\n" +
	"\t_file_url2\x9f\x02\n" +
	"\x04File\x12\x84\x01\n" +
	"\x10GenFileUploadUrl\x12&.api.system.v1.GenFileUploadUrlRequest\x1a$.api.system.v1.GenFileUploadUrlReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/file/upload-url\x12\x8f\x01\n" +
	"\x12FileUploadCallback\x12(.api.system.v1.FileUploadCallbackRequest\x1a&.api.system.v1.FileUploadCallbackReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/file/upload/finishedB4\n" +
	"\rapi.system.v1P\x01Z!spark/api/system/v1;v1b\x06proto3"

var (
	file_api_system_v1_file_proto_rawDescOnce sync.Once
	file_api_system_v1_file_proto_rawDescData []byte
)

func file_api_system_v1_file_proto_rawDescGZIP() []byte {
	file_api_system_v1_file_proto_rawDescOnce.Do(func() {
		file_api_system_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1_file_proto_rawDesc), len(file_api_system_v1_file_proto_rawDesc)))
	})
	return file_api_system_v1_file_proto_rawDescData
}

var file_api_system_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_system_v1_file_proto_goTypes = []any{
	(*GenFileUploadUrlRequest)(nil),             // 0: api.system.v1.GenFileUploadUrlRequest
	(*GenFileUploadUrlReply)(nil),               // 1: api.system.v1.GenFileUploadUrlReply
	(*FileUploadCallbackRequest)(nil),           // 2: api.system.v1.FileUploadCallbackRequest
	(*FileUploadCallbackReply)(nil),             // 3: api.system.v1.FileUploadCallbackReply
	(*GenFileUploadUrlRequest_Callback)(nil),    // 4: api.system.v1.GenFileUploadUrlRequest.Callback
	(*GenFileUploadUrlReply_Sts)(nil),           // 5: api.system.v1.GenFileUploadUrlReply.Sts
	(*GenFileUploadUrlReply_Url)(nil),           // 6: api.system.v1.GenFileUploadUrlReply.Url
	nil,                                         // 7: api.system.v1.GenFileUploadUrlReply.Url.SignedHeadersEntry
	nil,                                         // 8: api.system.v1.FileUploadCallbackRequest.CustomVarsEntry
	(*FileUploadCallbackRequest_ImageInfo)(nil), // 9: api.system.v1.FileUploadCallbackRequest.ImageInfo
}
var file_api_system_v1_file_proto_depIdxs = []int32{
	4, // 0: api.system.v1.GenFileUploadUrlRequest.callback:type_name -> api.system.v1.GenFileUploadUrlRequest.Callback
	5, // 1: api.system.v1.GenFileUploadUrlReply.sts:type_name -> api.system.v1.GenFileUploadUrlReply.Sts
	6, // 2: api.system.v1.GenFileUploadUrlReply.url:type_name -> api.system.v1.GenFileUploadUrlReply.Url
	9, // 3: api.system.v1.FileUploadCallbackRequest.image_info:type_name -> api.system.v1.FileUploadCallbackRequest.ImageInfo
	8, // 4: api.system.v1.FileUploadCallbackRequest.custom_vars:type_name -> api.system.v1.FileUploadCallbackRequest.CustomVarsEntry
	7, // 5: api.system.v1.GenFileUploadUrlReply.Url.signed_headers:type_name -> api.system.v1.GenFileUploadUrlReply.Url.SignedHeadersEntry
	0, // 6: api.system.v1.File.GenFileUploadUrl:input_type -> api.system.v1.GenFileUploadUrlRequest
	2, // 7: api.system.v1.File.FileUploadCallback:input_type -> api.system.v1.FileUploadCallbackRequest
	1, // 8: api.system.v1.File.GenFileUploadUrl:output_type -> api.system.v1.GenFileUploadUrlReply
	3, // 9: api.system.v1.File.FileUploadCallback:output_type -> api.system.v1.FileUploadCallbackReply
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_system_v1_file_proto_init() }
func file_api_system_v1_file_proto_init() {
	if File_api_system_v1_file_proto != nil {
		return
	}
	file_api_system_v1_file_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_system_v1_file_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_system_v1_file_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_system_v1_file_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1_file_proto_rawDesc), len(file_api_system_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_v1_file_proto_goTypes,
		DependencyIndexes: file_api_system_v1_file_proto_depIdxs,
		MessageInfos:      file_api_system_v1_file_proto_msgTypes,
	}.Build()
	File_api_system_v1_file_proto = out.File
	file_api_system_v1_file_proto_goTypes = nil
	file_api_system_v1_file_proto_depIdxs = nil
}
