// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/system/v1/menu.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MenuInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuInfoMultiError, or nil
// if none found.
func (m *MenuInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Pid

	// no validation rules for Name

	// no validation rules for Title

	// no validation rules for Icon

	// no validation rules for Condition

	if _, ok := _MenuInfo_MenuType_InLookup[m.GetMenuType()]; !ok {
		err := MenuInfoValidationError{
			field:  "MenuType",
			reason: "value must be in list [0 1 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Weight

	if _, ok := _MenuInfo_IsShow_InLookup[m.GetIsShow()]; !ok {
		err := MenuInfoValidationError{
			field:  "IsShow",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Path

	// no validation rules for Component

	if _, ok := _MenuInfo_IsLink_InLookup[m.GetIsLink()]; !ok {
		err := MenuInfoValidationError{
			field:  "IsLink",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ModuleType

	// no validation rules for ModelId

	if _, ok := _MenuInfo_IsIframe_InLookup[m.GetIsIframe()]; !ok {
		err := MenuInfoValidationError{
			field:  "IsIframe",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _MenuInfo_IsCached_InLookup[m.GetIsCached()]; !ok {
		err := MenuInfoValidationError{
			field:  "IsCached",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Redirect

	if _, ok := _MenuInfo_IsAffix_InLookup[m.GetIsAffix()]; !ok {
		err := MenuInfoValidationError{
			field:  "IsAffix",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for LinkUrl

	// no validation rules for CreatedBy

	// no validation rules for UpdatedBy

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuInfoValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuInfoValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuInfoValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Remark != nil {
		// no validation rules for Remark
	}

	if len(errors) > 0 {
		return MenuInfoMultiError(errors)
	}

	return nil
}

// MenuInfoMultiError is an error wrapping multiple validation errors returned
// by MenuInfo.ValidateAll() if the designated constraints aren't met.
type MenuInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuInfoMultiError) AllErrors() []error { return m }

// MenuInfoValidationError is the validation error returned by
// MenuInfo.Validate if the designated constraints aren't met.
type MenuInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuInfoValidationError) ErrorName() string { return "MenuInfoValidationError" }

// Error satisfies the builtin error interface
func (e MenuInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuInfoValidationError{}

var _MenuInfo_MenuType_InLookup = map[int32]struct{}{
	0: {},
	1: {},
	2: {},
}

var _MenuInfo_IsShow_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _MenuInfo_IsLink_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _MenuInfo_IsIframe_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _MenuInfo_IsCached_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _MenuInfo_IsAffix_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on CreateMenuRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMenuRequestMultiError, or nil if none found.
func (m *CreateMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Pid

	// no validation rules for Name

	// no validation rules for Title

	// no validation rules for Icon

	// no validation rules for Condition

	if _, ok := _CreateMenuRequest_MenuType_InLookup[m.GetMenuType()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "MenuType",
			reason: "value must be in list [0 1 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Weight

	if _, ok := _CreateMenuRequest_IsShow_InLookup[m.GetIsShow()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "IsShow",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Path

	// no validation rules for Component

	if _, ok := _CreateMenuRequest_IsLink_InLookup[m.GetIsLink()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "IsLink",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ModuleType

	// no validation rules for ModelId

	if _, ok := _CreateMenuRequest_IsIframe_InLookup[m.GetIsIframe()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "IsIframe",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreateMenuRequest_IsCached_InLookup[m.GetIsCached()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "IsCached",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Redirect

	if _, ok := _CreateMenuRequest_IsAffix_InLookup[m.GetIsAffix()]; !ok {
		err := CreateMenuRequestValidationError{
			field:  "IsAffix",
			reason: "value must be in list [0 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for LinkUrl

	if m.Remark != nil {
		// no validation rules for Remark
	}

	if len(errors) > 0 {
		return CreateMenuRequestMultiError(errors)
	}

	return nil
}

// CreateMenuRequestMultiError is an error wrapping multiple validation errors
// returned by CreateMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMenuRequestMultiError) AllErrors() []error { return m }

// CreateMenuRequestValidationError is the validation error returned by
// CreateMenuRequest.Validate if the designated constraints aren't met.
type CreateMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMenuRequestValidationError) ErrorName() string {
	return "CreateMenuRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMenuRequestValidationError{}

var _CreateMenuRequest_MenuType_InLookup = map[int32]struct{}{
	0: {},
	1: {},
	2: {},
}

var _CreateMenuRequest_IsShow_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _CreateMenuRequest_IsLink_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _CreateMenuRequest_IsIframe_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _CreateMenuRequest_IsCached_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _CreateMenuRequest_IsAffix_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on CreateMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMenuReplyMultiError, or nil if none found.
func (m *CreateMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateMenuReplyMultiError(errors)
	}

	return nil
}

// CreateMenuReplyMultiError is an error wrapping multiple validation errors
// returned by CreateMenuReply.ValidateAll() if the designated constraints
// aren't met.
type CreateMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMenuReplyMultiError) AllErrors() []error { return m }

// CreateMenuReplyValidationError is the validation error returned by
// CreateMenuReply.Validate if the designated constraints aren't met.
type CreateMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMenuReplyValidationError) ErrorName() string { return "CreateMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMenuReplyValidationError{}

// Validate checks the field values on UpdateMenuRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateMenuRequestMultiError, or nil if none found.
func (m *UpdateMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Title != nil {
		// no validation rules for Title
	}

	if m.Icon != nil {
		// no validation rules for Icon
	}

	if m.Condition != nil {
		// no validation rules for Condition
	}

	if m.Remark != nil {
		// no validation rules for Remark
	}

	if m.MenuType != nil {

		if _, ok := _UpdateMenuRequest_MenuType_InLookup[m.GetMenuType()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "MenuType",
				reason: "value must be in list [0 1 2]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Weight != nil {
		// no validation rules for Weight
	}

	if m.IsShow != nil {

		if _, ok := _UpdateMenuRequest_IsShow_InLookup[m.GetIsShow()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "IsShow",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Path != nil {
		// no validation rules for Path
	}

	if m.Component != nil {
		// no validation rules for Component
	}

	if m.IsLink != nil {

		if _, ok := _UpdateMenuRequest_IsLink_InLookup[m.GetIsLink()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "IsLink",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ModuleType != nil {
		// no validation rules for ModuleType
	}

	if m.ModelId != nil {
		// no validation rules for ModelId
	}

	if m.IsIframe != nil {

		if _, ok := _UpdateMenuRequest_IsIframe_InLookup[m.GetIsIframe()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "IsIframe",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.IsCached != nil {

		if _, ok := _UpdateMenuRequest_IsCached_InLookup[m.GetIsCached()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "IsCached",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Redirect != nil {
		// no validation rules for Redirect
	}

	if m.IsAffix != nil {

		if _, ok := _UpdateMenuRequest_IsAffix_InLookup[m.GetIsAffix()]; !ok {
			err := UpdateMenuRequestValidationError{
				field:  "IsAffix",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.LinkUrl != nil {
		// no validation rules for LinkUrl
	}

	if len(errors) > 0 {
		return UpdateMenuRequestMultiError(errors)
	}

	return nil
}

// UpdateMenuRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateMenuRequestMultiError) AllErrors() []error { return m }

// UpdateMenuRequestValidationError is the validation error returned by
// UpdateMenuRequest.Validate if the designated constraints aren't met.
type UpdateMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateMenuRequestValidationError) ErrorName() string {
	return "UpdateMenuRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateMenuRequestValidationError{}

var _UpdateMenuRequest_MenuType_InLookup = map[int32]struct{}{
	0: {},
	1: {},
	2: {},
}

var _UpdateMenuRequest_IsShow_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _UpdateMenuRequest_IsLink_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _UpdateMenuRequest_IsIframe_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _UpdateMenuRequest_IsCached_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

var _UpdateMenuRequest_IsAffix_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on UpdateMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateMenuReplyMultiError, or nil if none found.
func (m *UpdateMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateMenuReplyMultiError(errors)
	}

	return nil
}

// UpdateMenuReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateMenuReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateMenuReplyMultiError) AllErrors() []error { return m }

// UpdateMenuReplyValidationError is the validation error returned by
// UpdateMenuReply.Validate if the designated constraints aren't met.
type UpdateMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateMenuReplyValidationError) ErrorName() string { return "UpdateMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e UpdateMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateMenuReplyValidationError{}

// Validate checks the field values on DeleteMenuRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMenuRequestMultiError, or nil if none found.
func (m *DeleteMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteMenuRequestMultiError(errors)
	}

	return nil
}

// DeleteMenuRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMenuRequestMultiError) AllErrors() []error { return m }

// DeleteMenuRequestValidationError is the validation error returned by
// DeleteMenuRequest.Validate if the designated constraints aren't met.
type DeleteMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMenuRequestValidationError) ErrorName() string {
	return "DeleteMenuRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMenuRequestValidationError{}

// Validate checks the field values on DeleteMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMenuReplyMultiError, or nil if none found.
func (m *DeleteMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteMenuReplyMultiError(errors)
	}

	return nil
}

// DeleteMenuReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteMenuReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMenuReplyMultiError) AllErrors() []error { return m }

// DeleteMenuReplyValidationError is the validation error returned by
// DeleteMenuReply.Validate if the designated constraints aren't met.
type DeleteMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMenuReplyValidationError) ErrorName() string { return "DeleteMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeleteMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMenuReplyValidationError{}

// Validate checks the field values on GetMenuRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMenuRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMenuRequestMultiError,
// or nil if none found.
func (m *GetMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetMenuRequestMultiError(errors)
	}

	return nil
}

// GetMenuRequestMultiError is an error wrapping multiple validation errors
// returned by GetMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMenuRequestMultiError) AllErrors() []error { return m }

// GetMenuRequestValidationError is the validation error returned by
// GetMenuRequest.Validate if the designated constraints aren't met.
type GetMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMenuRequestValidationError) ErrorName() string { return "GetMenuRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMenuRequestValidationError{}

// Validate checks the field values on GetMenuReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMenuReplyMultiError, or
// nil if none found.
func (m *GetMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMenu()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMenuReplyValidationError{
					field:  "Menu",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMenuReplyValidationError{
					field:  "Menu",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMenu()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMenuReplyValidationError{
				field:  "Menu",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMenuReplyMultiError(errors)
	}

	return nil
}

// GetMenuReplyMultiError is an error wrapping multiple validation errors
// returned by GetMenuReply.ValidateAll() if the designated constraints aren't met.
type GetMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMenuReplyMultiError) AllErrors() []error { return m }

// GetMenuReplyValidationError is the validation error returned by
// GetMenuReply.Validate if the designated constraints aren't met.
type GetMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMenuReplyValidationError) ErrorName() string { return "GetMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMenuReplyValidationError{}

// Validate checks the field values on ListMenuRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMenuRequestMultiError, or nil if none found.
func (m *ListMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CurrentPage

	// no validation rules for PageSize

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.IsShow != nil {

		if _, ok := _ListMenuRequest_IsShow_InLookup[m.GetIsShow()]; !ok {
			err := ListMenuRequestValidationError{
				field:  "IsShow",
				reason: "value must be in list [0 1]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ListMenuRequestMultiError(errors)
	}

	return nil
}

// ListMenuRequestMultiError is an error wrapping multiple validation errors
// returned by ListMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMenuRequestMultiError) AllErrors() []error { return m }

// ListMenuRequestValidationError is the validation error returned by
// ListMenuRequest.Validate if the designated constraints aren't met.
type ListMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMenuRequestValidationError) ErrorName() string { return "ListMenuRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMenuRequestValidationError{}

var _ListMenuRequest_IsShow_InLookup = map[int32]struct{}{
	0: {},
	1: {},
}

// Validate checks the field values on ListMenuReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListMenuReplyMultiError, or
// nil if none found.
func (m *ListMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMenuReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMenuReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMenuReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListMenuReplyMultiError(errors)
	}

	return nil
}

// ListMenuReplyMultiError is an error wrapping multiple validation errors
// returned by ListMenuReply.ValidateAll() if the designated constraints
// aren't met.
type ListMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMenuReplyMultiError) AllErrors() []error { return m }

// ListMenuReplyValidationError is the validation error returned by
// ListMenuReply.Validate if the designated constraints aren't met.
type ListMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMenuReplyValidationError) ErrorName() string { return "ListMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMenuReplyValidationError{}

// Validate checks the field values on ListAllMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAllMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAllMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAllMenuRequestMultiError, or nil if none found.
func (m *ListAllMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAllMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListAllMenuRequestMultiError(errors)
	}

	return nil
}

// ListAllMenuRequestMultiError is an error wrapping multiple validation errors
// returned by ListAllMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type ListAllMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAllMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAllMenuRequestMultiError) AllErrors() []error { return m }

// ListAllMenuRequestValidationError is the validation error returned by
// ListAllMenuRequest.Validate if the designated constraints aren't met.
type ListAllMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAllMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAllMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAllMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAllMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAllMenuRequestValidationError) ErrorName() string {
	return "ListAllMenuRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAllMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAllMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAllMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAllMenuRequestValidationError{}

// Validate checks the field values on ListAllMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAllMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAllMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAllMenuReplyMultiError, or nil if none found.
func (m *ListAllMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAllMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAllMenuReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAllMenuReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAllMenuReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAllMenuReplyMultiError(errors)
	}

	return nil
}

// ListAllMenuReplyMultiError is an error wrapping multiple validation errors
// returned by ListAllMenuReply.ValidateAll() if the designated constraints
// aren't met.
type ListAllMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAllMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAllMenuReplyMultiError) AllErrors() []error { return m }

// ListAllMenuReplyValidationError is the validation error returned by
// ListAllMenuReply.Validate if the designated constraints aren't met.
type ListAllMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAllMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAllMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAllMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAllMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAllMenuReplyValidationError) ErrorName() string { return "ListAllMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListAllMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAllMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAllMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAllMenuReplyValidationError{}

// Validate checks the field values on CheckMenuPermissionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMenuPermissionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMenuPermissionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckMenuPermissionRequestMultiError, or nil if none found.
func (m *CheckMenuPermissionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMenuPermissionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for MenuId

	// no validation rules for Action

	if len(errors) > 0 {
		return CheckMenuPermissionRequestMultiError(errors)
	}

	return nil
}

// CheckMenuPermissionRequestMultiError is an error wrapping multiple
// validation errors returned by CheckMenuPermissionRequest.ValidateAll() if
// the designated constraints aren't met.
type CheckMenuPermissionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMenuPermissionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMenuPermissionRequestMultiError) AllErrors() []error { return m }

// CheckMenuPermissionRequestValidationError is the validation error returned
// by CheckMenuPermissionRequest.Validate if the designated constraints aren't met.
type CheckMenuPermissionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMenuPermissionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMenuPermissionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMenuPermissionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMenuPermissionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMenuPermissionRequestValidationError) ErrorName() string {
	return "CheckMenuPermissionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMenuPermissionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMenuPermissionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMenuPermissionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMenuPermissionRequestValidationError{}

// Validate checks the field values on CheckMenuPermissionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMenuPermissionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMenuPermissionReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckMenuPermissionReplyMultiError, or nil if none found.
func (m *CheckMenuPermissionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMenuPermissionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HasPermission

	if len(errors) > 0 {
		return CheckMenuPermissionReplyMultiError(errors)
	}

	return nil
}

// CheckMenuPermissionReplyMultiError is an error wrapping multiple validation
// errors returned by CheckMenuPermissionReply.ValidateAll() if the designated
// constraints aren't met.
type CheckMenuPermissionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMenuPermissionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMenuPermissionReplyMultiError) AllErrors() []error { return m }

// CheckMenuPermissionReplyValidationError is the validation error returned by
// CheckMenuPermissionReply.Validate if the designated constraints aren't met.
type CheckMenuPermissionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMenuPermissionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMenuPermissionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMenuPermissionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMenuPermissionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMenuPermissionReplyValidationError) ErrorName() string {
	return "CheckMenuPermissionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMenuPermissionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMenuPermissionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMenuPermissionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMenuPermissionReplyValidationError{}

// Validate checks the field values on MenuActions with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuActions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuActions with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuActionsMultiError, or
// nil if none found.
func (m *MenuActions) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuActions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MenuActionsMultiError(errors)
	}

	return nil
}

// MenuActionsMultiError is an error wrapping multiple validation errors
// returned by MenuActions.ValidateAll() if the designated constraints aren't met.
type MenuActionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuActionsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuActionsMultiError) AllErrors() []error { return m }

// MenuActionsValidationError is the validation error returned by
// MenuActions.Validate if the designated constraints aren't met.
type MenuActionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuActionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuActionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuActionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuActionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuActionsValidationError) ErrorName() string { return "MenuActionsValidationError" }

// Error satisfies the builtin error interface
func (e MenuActionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuActions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuActionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuActionsValidationError{}

// Validate checks the field values on MenuPermission with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuPermission) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuPermission with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuPermissionMultiError,
// or nil if none found.
func (m *MenuPermission) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuPermission) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MenuId

	// no validation rules for Action

	if len(errors) > 0 {
		return MenuPermissionMultiError(errors)
	}

	return nil
}

// MenuPermissionMultiError is an error wrapping multiple validation errors
// returned by MenuPermission.ValidateAll() if the designated constraints
// aren't met.
type MenuPermissionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuPermissionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuPermissionMultiError) AllErrors() []error { return m }

// MenuPermissionValidationError is the validation error returned by
// MenuPermission.Validate if the designated constraints aren't met.
type MenuPermissionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuPermissionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuPermissionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuPermissionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuPermissionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuPermissionValidationError) ErrorName() string { return "MenuPermissionValidationError" }

// Error satisfies the builtin error interface
func (e MenuPermissionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuPermission.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuPermissionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuPermissionValidationError{}

// Validate checks the field values on CheckMultiplePermissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMultiplePermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMultiplePermissionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CheckMultiplePermissionsRequestMultiError, or nil if none found.
func (m *CheckMultiplePermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMultiplePermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	for idx, item := range m.GetPermissions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CheckMultiplePermissionsRequestValidationError{
						field:  fmt.Sprintf("Permissions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CheckMultiplePermissionsRequestValidationError{
						field:  fmt.Sprintf("Permissions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CheckMultiplePermissionsRequestValidationError{
					field:  fmt.Sprintf("Permissions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CheckMultiplePermissionsRequestMultiError(errors)
	}

	return nil
}

// CheckMultiplePermissionsRequestMultiError is an error wrapping multiple
// validation errors returned by CheckMultiplePermissionsRequest.ValidateAll()
// if the designated constraints aren't met.
type CheckMultiplePermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMultiplePermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMultiplePermissionsRequestMultiError) AllErrors() []error { return m }

// CheckMultiplePermissionsRequestValidationError is the validation error
// returned by CheckMultiplePermissionsRequest.Validate if the designated
// constraints aren't met.
type CheckMultiplePermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMultiplePermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMultiplePermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMultiplePermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMultiplePermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMultiplePermissionsRequestValidationError) ErrorName() string {
	return "CheckMultiplePermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMultiplePermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMultiplePermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMultiplePermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMultiplePermissionsRequestValidationError{}

// Validate checks the field values on CheckMultiplePermissionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckMultiplePermissionsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckMultiplePermissionsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CheckMultiplePermissionsReplyMultiError, or nil if none found.
func (m *CheckMultiplePermissionsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckMultiplePermissionsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Results

	if len(errors) > 0 {
		return CheckMultiplePermissionsReplyMultiError(errors)
	}

	return nil
}

// CheckMultiplePermissionsReplyMultiError is an error wrapping multiple
// validation errors returned by CheckMultiplePermissionsReply.ValidateAll()
// if the designated constraints aren't met.
type CheckMultiplePermissionsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckMultiplePermissionsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckMultiplePermissionsReplyMultiError) AllErrors() []error { return m }

// CheckMultiplePermissionsReplyValidationError is the validation error
// returned by CheckMultiplePermissionsReply.Validate if the designated
// constraints aren't met.
type CheckMultiplePermissionsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckMultiplePermissionsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckMultiplePermissionsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckMultiplePermissionsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckMultiplePermissionsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckMultiplePermissionsReplyValidationError) ErrorName() string {
	return "CheckMultiplePermissionsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CheckMultiplePermissionsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckMultiplePermissionsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckMultiplePermissionsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckMultiplePermissionsReplyValidationError{}
