// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/system/v1/message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 消息标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 消息内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 消息类型（1系统消息 2通知公告）
	MessageType int32 `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 优先级（1低 2中 3高）
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// 发送者ID
	SenderId int64 `protobuf:"varint,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// 发送者名称
	SenderName string `protobuf:"bytes,7,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	// 接收者ID列表
	ReceiverIds []int64 `protobuf:"varint,8,rep,packed,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	// 接收者名称列表
	ReceiverNames []string `protobuf:"bytes,9,rep,name=receiver_names,json=receiverNames,proto3" json:"receiver_names,omitempty"`
	// 状态（0未读 1已读）
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     int64 `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_api_system_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInfo) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MessageInfo) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageInfo) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageInfo) GetReceiverIds() []int64 {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

func (x *MessageInfo) GetReceiverNames() []string {
	if x != nil {
		return x.ReceiverNames
	}
	return nil
}

func (x *MessageInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MessageInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息标题
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 消息内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 消息类型
	MessageType int32 `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 优先级
	Priority int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	// 接收者ID列表
	ReceiverIds   []int64 `protobuf:"varint,5,rep,packed,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *CreateMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateMessageRequest) GetReceiverIds() []int64 {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

type CreateMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageReply) Reset() {
	*x = CreateMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageReply) ProtoMessage() {}

func (x *CreateMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageReply.ProtoReflect.Descriptor instead.
func (*CreateMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMessageReply) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 消息标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 消息内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 消息类型
	MessageType int32 `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 优先级
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// 接收者ID列表
	ReceiverIds   []int64 `protobuf:"varint,6,rep,packed,name=receiver_ids,json=receiverIds,proto3" json:"receiver_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *UpdateMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateMessageRequest) GetReceiverIds() []int64 {
	if x != nil {
		return x.ReceiverIds
	}
	return nil
}

type UpdateMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageReply) Reset() {
	*x = UpdateMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageReply) ProtoMessage() {}

func (x *UpdateMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageReply.ProtoReflect.Descriptor instead.
func (*UpdateMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMessageReply) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageReply) Reset() {
	*x = DeleteMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageReply) ProtoMessage() {}

func (x *DeleteMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageReply.ProtoReflect.Descriptor instead.
func (*DeleteMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageReply) Reset() {
	*x = GetMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageReply) ProtoMessage() {}

func (x *GetMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageReply.ProtoReflect.Descriptor instead.
func (*GetMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageReply) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每页数量
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 页码
	Current int32 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	// 消息类型，用于筛选
	MessageType int32 `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 状态，用于筛选 0 系统 1 对多
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 开始时间
	BeginTime int64 `protobuf:"varint,5,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	// 结束时间
	EndTime       int64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageRequest) Reset() {
	*x = ListMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageRequest) ProtoMessage() {}

func (x *ListMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageRequest.ProtoReflect.Descriptor instead.
func (*ListMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *ListMessageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMessageRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *ListMessageRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListMessageRequest) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *ListMessageRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ListMessageReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息列表
	Items []*MessageInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageReply) Reset() {
	*x = ListMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageReply) ProtoMessage() {}

func (x *ListMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageReply.ProtoReflect.Descriptor instead.
func (*ListMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessageReply) GetItems() []*MessageInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMessageReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReadMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageRequest) Reset() {
	*x = ReadMessageRequest{}
	mi := &file_api_system_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageRequest) ProtoMessage() {}

func (x *ReadMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageRequest.ProtoReflect.Descriptor instead.
func (*ReadMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *ReadMessageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageReply) Reset() {
	*x = ReadMessageReply{}
	mi := &file_api_system_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageReply) ProtoMessage() {}

func (x *ReadMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageReply.ProtoReflect.Descriptor instead.
func (*ReadMessageReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *ReadMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_system_v1_message_proto protoreflect.FileDescriptor

const file_api_system_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/system/v1/message.proto\x12\rapi.system.v1\x1a\x1cgoogle/api/annotations.proto\"\xea\x02\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\x05R\vmessageType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\a \x01(\tR\n" +
	"senderName\x12!\n" +
	"\freceiver_ids\x18\b \x03(\x03R\vreceiverIds\x12%\n" +
	"\x0ereceiver_names\x18\t \x03(\tR\rreceiverNames\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\xa8\x01\n" +
	"\x14CreateMessageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12!\n" +
	"\freceiver_ids\x18\x05 \x03(\x03R\vreceiverIds\"J\n" +
	"\x12CreateMessageReply\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.api.system.v1.MessageInfoR\amessage\"\xb8\x01\n" +
	"\x14UpdateMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\x05R\vmessageType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12!\n" +
	"\freceiver_ids\x18\x06 \x03(\x03R\vreceiverIds\"J\n" +
	"\x12UpdateMessageReply\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.api.system.v1.MessageInfoR\amessage\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x0fGetMessageReply\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.api.system.v1.MessageInfoR\amessage\"\xc0\x01\n" +
	"\x12ListMessageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x05 \x01(\x03R\tbeginTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\"Z\n" +
	"\x10ListMessageReply\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.api.system.v1.MessageInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"$\n" +
	"\x12ReadMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x10ReadMessageReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf4\x05\n" +
	"\aMessage\x12z\n" +
	"\rCreateMessage\x12#.api.system.v1.CreateMessageRequest\x1a!.api.system.v1.CreateMessageReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/system/message\x12\x81\x01\n" +
	"\rUpdateMessage\x12#.api.system.v1.UpdateMessageRequest\x1a!.api.system.v1.UpdateMessageReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/system/message/update\x12\x81\x01\n" +
	"\rDeleteMessage\x12#.api.system.v1.DeleteMessageRequest\x1a!.api.system.v1.DeleteMessageReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/system/message/delete\x12r\n" +
	"\n" +
	"GetMessage\x12 .api.system.v1.GetMessageRequest\x1a\x1e.api.system.v1.GetMessageReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/system/message/get\x12v\n" +
	"\vListMessage\x12!.api.system.v1.ListMessageRequest\x1a\x1f.api.system.v1.ListMessageReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/system/message/list\x12y\n" +
	"\vReadMessage\x12!.api.system.v1.ReadMessageRequest\x1a\x1f.api.system.v1.ReadMessageReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/system/message/readB4\n" +
	"\rapi.system.v1P\x01Z!spark/api/system/v1;v1b\x06proto3"

var (
	file_api_system_v1_message_proto_rawDescOnce sync.Once
	file_api_system_v1_message_proto_rawDescData []byte
)

func file_api_system_v1_message_proto_rawDescGZIP() []byte {
	file_api_system_v1_message_proto_rawDescOnce.Do(func() {
		file_api_system_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1_message_proto_rawDesc), len(file_api_system_v1_message_proto_rawDesc)))
	})
	return file_api_system_v1_message_proto_rawDescData
}

var file_api_system_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_system_v1_message_proto_goTypes = []any{
	(*MessageInfo)(nil),          // 0: api.system.v1.MessageInfo
	(*CreateMessageRequest)(nil), // 1: api.system.v1.CreateMessageRequest
	(*CreateMessageReply)(nil),   // 2: api.system.v1.CreateMessageReply
	(*UpdateMessageRequest)(nil), // 3: api.system.v1.UpdateMessageRequest
	(*UpdateMessageReply)(nil),   // 4: api.system.v1.UpdateMessageReply
	(*DeleteMessageRequest)(nil), // 5: api.system.v1.DeleteMessageRequest
	(*DeleteMessageReply)(nil),   // 6: api.system.v1.DeleteMessageReply
	(*GetMessageRequest)(nil),    // 7: api.system.v1.GetMessageRequest
	(*GetMessageReply)(nil),      // 8: api.system.v1.GetMessageReply
	(*ListMessageRequest)(nil),   // 9: api.system.v1.ListMessageRequest
	(*ListMessageReply)(nil),     // 10: api.system.v1.ListMessageReply
	(*ReadMessageRequest)(nil),   // 11: api.system.v1.ReadMessageRequest
	(*ReadMessageReply)(nil),     // 12: api.system.v1.ReadMessageReply
}
var file_api_system_v1_message_proto_depIdxs = []int32{
	0,  // 0: api.system.v1.CreateMessageReply.message:type_name -> api.system.v1.MessageInfo
	0,  // 1: api.system.v1.UpdateMessageReply.message:type_name -> api.system.v1.MessageInfo
	0,  // 2: api.system.v1.GetMessageReply.message:type_name -> api.system.v1.MessageInfo
	0,  // 3: api.system.v1.ListMessageReply.items:type_name -> api.system.v1.MessageInfo
	1,  // 4: api.system.v1.Message.CreateMessage:input_type -> api.system.v1.CreateMessageRequest
	3,  // 5: api.system.v1.Message.UpdateMessage:input_type -> api.system.v1.UpdateMessageRequest
	5,  // 6: api.system.v1.Message.DeleteMessage:input_type -> api.system.v1.DeleteMessageRequest
	7,  // 7: api.system.v1.Message.GetMessage:input_type -> api.system.v1.GetMessageRequest
	9,  // 8: api.system.v1.Message.ListMessage:input_type -> api.system.v1.ListMessageRequest
	11, // 9: api.system.v1.Message.ReadMessage:input_type -> api.system.v1.ReadMessageRequest
	2,  // 10: api.system.v1.Message.CreateMessage:output_type -> api.system.v1.CreateMessageReply
	4,  // 11: api.system.v1.Message.UpdateMessage:output_type -> api.system.v1.UpdateMessageReply
	6,  // 12: api.system.v1.Message.DeleteMessage:output_type -> api.system.v1.DeleteMessageReply
	8,  // 13: api.system.v1.Message.GetMessage:output_type -> api.system.v1.GetMessageReply
	10, // 14: api.system.v1.Message.ListMessage:output_type -> api.system.v1.ListMessageReply
	12, // 15: api.system.v1.Message.ReadMessage:output_type -> api.system.v1.ReadMessageReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_system_v1_message_proto_init() }
func file_api_system_v1_message_proto_init() {
	if File_api_system_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1_message_proto_rawDesc), len(file_api_system_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_v1_message_proto_goTypes,
		DependencyIndexes: file_api_system_v1_message_proto_depIdxs,
		MessageInfos:      file_api_system_v1_message_proto_msgTypes,
	}.Build()
	File_api_system_v1_message_proto = out.File
	file_api_system_v1_message_proto_goTypes = nil
	file_api_system_v1_message_proto_depIdxs = nil
}
