// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/system/v1/post.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 岗位编码
	PostCode string `protobuf:"bytes,2,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	// 岗位名称
	PostName string `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	// 显示顺序
	Sort int32 `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// 状态(0停用 1正常)
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_api_system_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *PostInfo) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PostInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PostInfo) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *PostInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PostInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位编码
	PostCode string `protobuf:"bytes,1,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	// 岗位名称
	PostName string `protobuf:"bytes,2,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	// 显示顺序
	Sort int32 `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 状态(0停用 1正常)
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark        *string `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_api_system_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostRequest) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *CreatePostRequest) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *CreatePostRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreatePostRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreatePostRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

type CreatePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReply) Reset() {
	*x = CreatePostReply{}
	mi := &file_api_system_v1_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReply) ProtoMessage() {}

func (x *CreatePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReply.ProtoReflect.Descriptor instead.
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{2}
}

type UpdatePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 岗位编码
	PostCode string `protobuf:"bytes,2,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	// 岗位名称
	PostName string `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	// 显示顺序
	Sort int32 `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// 状态(0停用 1正常)
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// 备注
	Remark        *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_api_system_v1_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostRequest) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *UpdatePostRequest) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *UpdatePostRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdatePostRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatePostRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

type UpdatePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostReply) Reset() {
	*x = UpdatePostReply{}
	mi := &file_api_system_v1_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReply) ProtoMessage() {}

func (x *UpdatePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReply.ProtoReflect.Descriptor instead.
func (*UpdatePostReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{4}
}

type DeletePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_api_system_v1_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostReply) Reset() {
	*x = DeletePostReply{}
	mi := &file_api_system_v1_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReply) ProtoMessage() {}

func (x *DeletePostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReply.ProtoReflect.Descriptor instead.
func (*DeletePostReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{6}
}

type GetPostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_api_system_v1_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *PostInfo              `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostReply) Reset() {
	*x = GetPostReply{}
	mi := &file_api_system_v1_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostReply) ProtoMessage() {}

func (x *GetPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostReply.ProtoReflect.Descriptor instead.
func (*GetPostReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostReply) GetPost() *PostInfo {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每页数量
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 页码
	Current int32 `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	// 岗位编码，用于筛选
	PostCode *string `protobuf:"bytes,3,opt,name=post_code,json=postCode,proto3,oneof" json:"post_code,omitempty"`
	// 岗位名称，用于筛选
	PostName *string `protobuf:"bytes,4,opt,name=post_name,json=postName,proto3,oneof" json:"post_name,omitempty"`
	// 状态筛选 0 停用 1 正常
	Status        *int32 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostRequest) Reset() {
	*x = ListPostRequest{}
	mi := &file_api_system_v1_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostRequest) ProtoMessage() {}

func (x *ListPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostRequest.ProtoReflect.Descriptor instead.
func (*ListPostRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{9}
}

func (x *ListPostRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPostRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListPostRequest) GetPostCode() string {
	if x != nil && x.PostCode != nil {
		return *x.PostCode
	}
	return ""
}

func (x *ListPostRequest) GetPostName() string {
	if x != nil && x.PostName != nil {
		return *x.PostName
	}
	return ""
}

func (x *ListPostRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type ListPostReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 岗位列表
	Items []*PostInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostReply) Reset() {
	*x = ListPostReply{}
	mi := &file_api_system_v1_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostReply) ProtoMessage() {}

func (x *ListPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostReply.ProtoReflect.Descriptor instead.
func (*ListPostReply) Descriptor() ([]byte, []int) {
	return file_api_system_v1_post_proto_rawDescGZIP(), []int{10}
}

func (x *ListPostReply) GetItems() []*PostInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPostReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_system_v1_post_proto protoreflect.FileDescriptor

const file_api_system_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x18api/system/v1/post.proto\x12\rapi.system.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xf1\x01\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpost_code\x18\x02 \x01(\tR\bpostCode\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12!\n" +
	"\x06status\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x040\x000\x01R\x06status\x12\x1b\n" +
	"\x06remark\x18\x06 \x01(\tH\x00R\x06remark\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAtB\t\n" +
	"\a_remark\"\xac\x01\n" +
	"\x11CreatePostRequest\x12\x1b\n" +
	"\tpost_code\x18\x01 \x01(\tR\bpostCode\x12\x1b\n" +
	"\tpost_name\x18\x02 \x01(\tR\bpostName\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12!\n" +
	"\x06status\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x040\x000\x01R\x06status\x12\x1b\n" +
	"\x06remark\x18\x05 \x01(\tH\x00R\x06remark\x88\x01\x01B\t\n" +
	"\a_remark\"\x11\n" +
	"\x0fCreatePostReply\"\xbc\x01\n" +
	"\x11UpdatePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpost_code\x18\x02 \x01(\tR\bpostCode\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12!\n" +
	"\x06status\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x040\x000\x01R\x06status\x12\x1b\n" +
	"\x06remark\x18\x06 \x01(\tH\x00R\x06remark\x88\x01\x01B\t\n" +
	"\a_remark\"\x11\n" +
	"\x0fUpdatePostReply\"#\n" +
	"\x11DeletePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeletePostReply\" \n" +
	"\x0eGetPostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\fGetPostReply\x12+\n" +
	"\x04post\x18\x01 \x01(\v2\x17.api.system.v1.PostInfoR\x04post\"\xd0\x01\n" +
	"\x0fListPostRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12 \n" +
	"\tpost_code\x18\x03 \x01(\tH\x00R\bpostCode\x88\x01\x01\x12 \n" +
	"\tpost_name\x18\x04 \x01(\tH\x01R\bpostName\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x05H\x02R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_post_codeB\f\n" +
	"\n" +
	"_post_nameB\t\n" +
	"\a_status\"T\n" +
	"\rListPostReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.api.system.v1.PostInfoR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xb8\x04\n" +
	"\x04Post\x12n\n" +
	"\n" +
	"CreatePost\x12 .api.system.v1.CreatePostRequest\x1a\x1e.api.system.v1.CreatePostReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/system/post\x12u\n" +
	"\n" +
	"UpdatePost\x12 .api.system.v1.UpdatePostRequest\x1a\x1e.api.system.v1.UpdatePostReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/system/post/update\x12u\n" +
	"\n" +
	"DeletePost\x12 .api.system.v1.DeletePostRequest\x1a\x1e.api.system.v1.DeletePostReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/system/post/delete\x12f\n" +
	"\aGetPost\x12\x1d.api.system.v1.GetPostRequest\x1a\x1b.api.system.v1.GetPostReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/system/post/get\x12j\n" +
	"\bListPost\x12\x1e.api.system.v1.ListPostRequest\x1a\x1c.api.system.v1.ListPostReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/system/post/listB4\n" +
	"\rapi.system.v1P\x01Z!spark/api/system/v1;v1b\x06proto3"

var (
	file_api_system_v1_post_proto_rawDescOnce sync.Once
	file_api_system_v1_post_proto_rawDescData []byte
)

func file_api_system_v1_post_proto_rawDescGZIP() []byte {
	file_api_system_v1_post_proto_rawDescOnce.Do(func() {
		file_api_system_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1_post_proto_rawDesc), len(file_api_system_v1_post_proto_rawDesc)))
	})
	return file_api_system_v1_post_proto_rawDescData
}

var file_api_system_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_system_v1_post_proto_goTypes = []any{
	(*PostInfo)(nil),          // 0: api.system.v1.PostInfo
	(*CreatePostRequest)(nil), // 1: api.system.v1.CreatePostRequest
	(*CreatePostReply)(nil),   // 2: api.system.v1.CreatePostReply
	(*UpdatePostRequest)(nil), // 3: api.system.v1.UpdatePostRequest
	(*UpdatePostReply)(nil),   // 4: api.system.v1.UpdatePostReply
	(*DeletePostRequest)(nil), // 5: api.system.v1.DeletePostRequest
	(*DeletePostReply)(nil),   // 6: api.system.v1.DeletePostReply
	(*GetPostRequest)(nil),    // 7: api.system.v1.GetPostRequest
	(*GetPostReply)(nil),      // 8: api.system.v1.GetPostReply
	(*ListPostRequest)(nil),   // 9: api.system.v1.ListPostRequest
	(*ListPostReply)(nil),     // 10: api.system.v1.ListPostReply
}
var file_api_system_v1_post_proto_depIdxs = []int32{
	0,  // 0: api.system.v1.GetPostReply.post:type_name -> api.system.v1.PostInfo
	0,  // 1: api.system.v1.ListPostReply.items:type_name -> api.system.v1.PostInfo
	1,  // 2: api.system.v1.Post.CreatePost:input_type -> api.system.v1.CreatePostRequest
	3,  // 3: api.system.v1.Post.UpdatePost:input_type -> api.system.v1.UpdatePostRequest
	5,  // 4: api.system.v1.Post.DeletePost:input_type -> api.system.v1.DeletePostRequest
	7,  // 5: api.system.v1.Post.GetPost:input_type -> api.system.v1.GetPostRequest
	9,  // 6: api.system.v1.Post.ListPost:input_type -> api.system.v1.ListPostRequest
	2,  // 7: api.system.v1.Post.CreatePost:output_type -> api.system.v1.CreatePostReply
	4,  // 8: api.system.v1.Post.UpdatePost:output_type -> api.system.v1.UpdatePostReply
	6,  // 9: api.system.v1.Post.DeletePost:output_type -> api.system.v1.DeletePostReply
	8,  // 10: api.system.v1.Post.GetPost:output_type -> api.system.v1.GetPostReply
	10, // 11: api.system.v1.Post.ListPost:output_type -> api.system.v1.ListPostReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_system_v1_post_proto_init() }
func file_api_system_v1_post_proto_init() {
	if File_api_system_v1_post_proto != nil {
		return
	}
	file_api_system_v1_post_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_system_v1_post_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_system_v1_post_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_system_v1_post_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1_post_proto_rawDesc), len(file_api_system_v1_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_v1_post_proto_goTypes,
		DependencyIndexes: file_api_system_v1_post_proto_depIdxs,
		MessageInfos:      file_api_system_v1_post_proto_msgTypes,
	}.Build()
	File_api_system_v1_post_proto = out.File
	file_api_system_v1_post_proto_goTypes = nil
	file_api_system_v1_post_proto_depIdxs = nil
}
