// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.31.1
// source: system/v1/user_online.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserOnlineForceLogout = "/api.system.v1.UserOnline/ForceLogout"
const OperationUserOnlineListUserOnline = "/api.system.v1.UserOnline/ListUserOnline"

type UserOnlineHTTPServer interface {
	ForceLogout(context.Context, *ForceLogoutRequest) (*ForceLogoutReply, error)
	ListUserOnline(context.Context, *ListUserOnlineRequest) (*ListUserOnlineReply, error)
}

func RegisterUserOnlineHTTPServer(s *http.Server, srv UserOnlineHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/system/user/online/list", _UserOnline_ListUserOnline0_HTTP_Handler(srv))
	r.POST("/api/v1/system/user/online/logout", _UserOnline_ForceLogout0_HTTP_Handler(srv))
}

func _UserOnline_ListUserOnline0_HTTP_Handler(srv UserOnlineHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUserOnlineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOnlineListUserOnline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserOnline(ctx, req.(*ListUserOnlineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUserOnlineReply)
		return ctx.Result(200, reply)
	}
}

func _UserOnline_ForceLogout0_HTTP_Handler(srv UserOnlineHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ForceLogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOnlineForceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ForceLogout(ctx, req.(*ForceLogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ForceLogoutReply)
		return ctx.Result(200, reply)
	}
}

type UserOnlineHTTPClient interface {
	ForceLogout(ctx context.Context, req *ForceLogoutRequest, opts ...http.CallOption) (rsp *ForceLogoutReply, err error)
	ListUserOnline(ctx context.Context, req *ListUserOnlineRequest, opts ...http.CallOption) (rsp *ListUserOnlineReply, err error)
}

type UserOnlineHTTPClientImpl struct {
	cc *http.Client
}

func NewUserOnlineHTTPClient(client *http.Client) UserOnlineHTTPClient {
	return &UserOnlineHTTPClientImpl{client}
}

func (c *UserOnlineHTTPClientImpl) ForceLogout(ctx context.Context, in *ForceLogoutRequest, opts ...http.CallOption) (*ForceLogoutReply, error) {
	var out ForceLogoutReply
	pattern := "/api/v1/system/user/online/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserOnlineForceLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserOnlineHTTPClientImpl) ListUserOnline(ctx context.Context, in *ListUserOnlineRequest, opts ...http.CallOption) (*ListUserOnlineReply, error) {
	var out ListUserOnlineReply
	pattern := "/api/v1/system/user/online/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserOnlineListUserOnline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
