[request_definition]
r = user, menu

[policy_definition]
p = role, menu

[role_definition]
g = _, _  # 用户, 角色

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.user, p.role) && r.menu == p.menu || r.user == 1