// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"spark/internal/data/dal/model"
)

func newSysOperLog(db *gorm.DB, opts ...gen.DOOption) sysOperLog {
	_sysOperLog := sysOperLog{}

	_sysOperLog.sysOperLogDo.UseDB(db, opts...)
	_sysOperLog.sysOperLogDo.UseModel(&model.SysOperLog{})

	tableName := _sysOperLog.sysOperLogDo.TableName()
	_sysOperLog.ALL = field.NewAsterisk(tableName)
	_sysOperLog.ID = field.NewInt64(tableName, "id")
	_sysOperLog.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysOperLog.Title = field.NewString(tableName, "title")
	_sysOperLog.BusinessType = field.NewInt32(tableName, "business_type")
	_sysOperLog.Method = field.NewString(tableName, "method")
	_sysOperLog.RequestMethod = field.NewString(tableName, "request_method")
	_sysOperLog.OperatorType = field.NewInt32(tableName, "operator_type")
	_sysOperLog.OperName = field.NewString(tableName, "oper_name")
	_sysOperLog.DeptName = field.NewString(tableName, "dept_name")
	_sysOperLog.OperURL = field.NewString(tableName, "oper_url")
	_sysOperLog.OperIP = field.NewString(tableName, "oper_ip")
	_sysOperLog.OperLocation = field.NewString(tableName, "oper_location")
	_sysOperLog.OperParam = field.NewString(tableName, "oper_param")
	_sysOperLog.ErrorMsg = field.NewString(tableName, "error_msg")
	_sysOperLog.CreatedAt = field.NewInt64(tableName, "created_at")

	_sysOperLog.fillFieldMap()

	return _sysOperLog
}

type sysOperLog struct {
	sysOperLogDo

	ALL           field.Asterisk
	ID            field.Int64
	CreatedBy     field.Int64
	Title         field.String
	BusinessType  field.Int32
	Method        field.String
	RequestMethod field.String
	OperatorType  field.Int32
	OperName      field.String
	DeptName      field.String
	OperURL       field.String
	OperIP        field.String
	OperLocation  field.String
	OperParam     field.String
	ErrorMsg      field.String
	CreatedAt     field.Int64

	fieldMap map[string]field.Expr
}

func (s sysOperLog) Table(newTableName string) *sysOperLog {
	s.sysOperLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOperLog) As(alias string) *sysOperLog {
	s.sysOperLogDo.DO = *(s.sysOperLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOperLog) updateTableName(table string) *sysOperLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.Title = field.NewString(table, "title")
	s.BusinessType = field.NewInt32(table, "business_type")
	s.Method = field.NewString(table, "method")
	s.RequestMethod = field.NewString(table, "request_method")
	s.OperatorType = field.NewInt32(table, "operator_type")
	s.OperName = field.NewString(table, "oper_name")
	s.DeptName = field.NewString(table, "dept_name")
	s.OperURL = field.NewString(table, "oper_url")
	s.OperIP = field.NewString(table, "oper_ip")
	s.OperLocation = field.NewString(table, "oper_location")
	s.OperParam = field.NewString(table, "oper_param")
	s.ErrorMsg = field.NewString(table, "error_msg")
	s.CreatedAt = field.NewInt64(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sysOperLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOperLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["title"] = s.Title
	s.fieldMap["business_type"] = s.BusinessType
	s.fieldMap["method"] = s.Method
	s.fieldMap["request_method"] = s.RequestMethod
	s.fieldMap["operator_type"] = s.OperatorType
	s.fieldMap["oper_name"] = s.OperName
	s.fieldMap["dept_name"] = s.DeptName
	s.fieldMap["oper_url"] = s.OperURL
	s.fieldMap["oper_ip"] = s.OperIP
	s.fieldMap["oper_location"] = s.OperLocation
	s.fieldMap["oper_param"] = s.OperParam
	s.fieldMap["error_msg"] = s.ErrorMsg
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sysOperLog) clone(db *gorm.DB) sysOperLog {
	s.sysOperLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOperLog) replaceDB(db *gorm.DB) sysOperLog {
	s.sysOperLogDo.ReplaceDB(db)
	return s
}

type sysOperLogDo struct{ gen.DO }

type ISysOperLogDo interface {
	gen.SubQuery
	Debug() ISysOperLogDo
	WithContext(ctx context.Context) ISysOperLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysOperLogDo
	WriteDB() ISysOperLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysOperLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysOperLogDo
	Not(conds ...gen.Condition) ISysOperLogDo
	Or(conds ...gen.Condition) ISysOperLogDo
	Select(conds ...field.Expr) ISysOperLogDo
	Where(conds ...gen.Condition) ISysOperLogDo
	Order(conds ...field.Expr) ISysOperLogDo
	Distinct(cols ...field.Expr) ISysOperLogDo
	Omit(cols ...field.Expr) ISysOperLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysOperLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysOperLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysOperLogDo
	Group(cols ...field.Expr) ISysOperLogDo
	Having(conds ...gen.Condition) ISysOperLogDo
	Limit(limit int) ISysOperLogDo
	Offset(offset int) ISysOperLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOperLogDo
	Unscoped() ISysOperLogDo
	Create(values ...*model.SysOperLog) error
	CreateInBatches(values []*model.SysOperLog, batchSize int) error
	Save(values ...*model.SysOperLog) error
	First() (*model.SysOperLog, error)
	Take() (*model.SysOperLog, error)
	Last() (*model.SysOperLog, error)
	Find() ([]*model.SysOperLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOperLog, err error)
	FindInBatches(result *[]*model.SysOperLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysOperLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysOperLogDo
	Assign(attrs ...field.AssignExpr) ISysOperLogDo
	Joins(fields ...field.RelationField) ISysOperLogDo
	Preload(fields ...field.RelationField) ISysOperLogDo
	FirstOrInit() (*model.SysOperLog, error)
	FirstOrCreate() (*model.SysOperLog, error)
	FindByPage(offset int, limit int) (result []*model.SysOperLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysOperLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysOperLogDo) Debug() ISysOperLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOperLogDo) WithContext(ctx context.Context) ISysOperLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOperLogDo) ReadDB() ISysOperLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOperLogDo) WriteDB() ISysOperLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOperLogDo) Session(config *gorm.Session) ISysOperLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOperLogDo) Clauses(conds ...clause.Expression) ISysOperLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOperLogDo) Returning(value interface{}, columns ...string) ISysOperLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOperLogDo) Not(conds ...gen.Condition) ISysOperLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOperLogDo) Or(conds ...gen.Condition) ISysOperLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOperLogDo) Select(conds ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOperLogDo) Where(conds ...gen.Condition) ISysOperLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOperLogDo) Order(conds ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOperLogDo) Distinct(cols ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOperLogDo) Omit(cols ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOperLogDo) Join(table schema.Tabler, on ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOperLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOperLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOperLogDo) Group(cols ...field.Expr) ISysOperLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOperLogDo) Having(conds ...gen.Condition) ISysOperLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOperLogDo) Limit(limit int) ISysOperLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOperLogDo) Offset(offset int) ISysOperLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOperLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOperLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOperLogDo) Unscoped() ISysOperLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOperLogDo) Create(values ...*model.SysOperLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOperLogDo) CreateInBatches(values []*model.SysOperLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOperLogDo) Save(values ...*model.SysOperLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOperLogDo) First() (*model.SysOperLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperLog), nil
	}
}

func (s sysOperLogDo) Take() (*model.SysOperLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperLog), nil
	}
}

func (s sysOperLogDo) Last() (*model.SysOperLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperLog), nil
	}
}

func (s sysOperLogDo) Find() ([]*model.SysOperLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysOperLog), err
}

func (s sysOperLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOperLog, err error) {
	buf := make([]*model.SysOperLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOperLogDo) FindInBatches(result *[]*model.SysOperLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOperLogDo) Attrs(attrs ...field.AssignExpr) ISysOperLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOperLogDo) Assign(attrs ...field.AssignExpr) ISysOperLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOperLogDo) Joins(fields ...field.RelationField) ISysOperLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOperLogDo) Preload(fields ...field.RelationField) ISysOperLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOperLogDo) FirstOrInit() (*model.SysOperLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperLog), nil
	}
}

func (s sysOperLogDo) FirstOrCreate() (*model.SysOperLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperLog), nil
	}
}

func (s sysOperLogDo) FindByPage(offset int, limit int) (result []*model.SysOperLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOperLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOperLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOperLogDo) Delete(models ...*model.SysOperLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOperLogDo) withDO(do gen.Dao) *sysOperLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
