// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common/v1/error.proto

// 定义包名

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_COMMON_ERROR                   ErrorReason = 0
	ErrorReason_COMMON_CONTENT_MISSING         ErrorReason = 1
	ErrorReason_COMMON_INTERNAL_ERROR          ErrorReason = 2
	ErrorReason_SYSTEM_USER_ERROR              ErrorReason = 100
	ErrorReason_SYSTEM_USER_NOT_FOUND          ErrorReason = 101
	ErrorReason_SYSTEM_AUTH_ERROR              ErrorReason = 102
	ErrorReason_SYSTEM_ROLE_ERROR              ErrorReason = 200
	ErrorReason_SYSTEM_MENU_ERROR              ErrorReason = 300
	ErrorReason_SYSTEM_PERMISSION_ERROR        ErrorReason = 400
	ErrorReason_SYSTEM_DICT_ERROR              ErrorReason = 500
	ErrorReason_SYSTEM_DEPT_ERROR              ErrorReason = 600
	ErrorReason_SYSTEM_POST_ERROR              ErrorReason = 700
	ErrorReason_SYSTEM_OSS_CONFIG_INVALID      ErrorReason = 900
	ErrorReason_SYSTEM_OSS_CONFIG_INCOMPLETE   ErrorReason = 901
	ErrorReason_SYSTEM_OSS_SERVICE_UNAVAILABLE ErrorReason = 902
	ErrorReason_SYSTEM_OSS_PROVIDER_NOT_FOUND  ErrorReason = 903
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "COMMON_ERROR",
		1:   "COMMON_CONTENT_MISSING",
		2:   "COMMON_INTERNAL_ERROR",
		100: "SYSTEM_USER_ERROR",
		101: "SYSTEM_USER_NOT_FOUND",
		102: "SYSTEM_AUTH_ERROR",
		200: "SYSTEM_ROLE_ERROR",
		300: "SYSTEM_MENU_ERROR",
		400: "SYSTEM_PERMISSION_ERROR",
		500: "SYSTEM_DICT_ERROR",
		600: "SYSTEM_DEPT_ERROR",
		700: "SYSTEM_POST_ERROR",
		900: "SYSTEM_OSS_CONFIG_INVALID",
		901: "SYSTEM_OSS_CONFIG_INCOMPLETE",
		902: "SYSTEM_OSS_SERVICE_UNAVAILABLE",
		903: "SYSTEM_OSS_PROVIDER_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"COMMON_ERROR":                   0,
		"COMMON_CONTENT_MISSING":         1,
		"COMMON_INTERNAL_ERROR":          2,
		"SYSTEM_USER_ERROR":              100,
		"SYSTEM_USER_NOT_FOUND":          101,
		"SYSTEM_AUTH_ERROR":              102,
		"SYSTEM_ROLE_ERROR":              200,
		"SYSTEM_MENU_ERROR":              300,
		"SYSTEM_PERMISSION_ERROR":        400,
		"SYSTEM_DICT_ERROR":              500,
		"SYSTEM_DEPT_ERROR":              600,
		"SYSTEM_POST_ERROR":              700,
		"SYSTEM_OSS_CONFIG_INVALID":      900,
		"SYSTEM_OSS_CONFIG_INCOMPLETE":   901,
		"SYSTEM_OSS_SERVICE_UNAVAILABLE": 902,
		"SYSTEM_OSS_PROVIDER_NOT_FOUND":  903,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_common_v1_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_error_proto protoreflect.FileDescriptor

const file_common_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/error.proto\x12\rapi.kratos.v1\x1a\x13errors/errors.proto*\x96\x03\n" +
	"\vErrorReason\x12\x10\n" +
	"\fCOMMON_ERROR\x10\x00\x12\x1a\n" +
	"\x16COMMON_CONTENT_MISSING\x10\x01\x12\x19\n" +
	"\x15COMMON_INTERNAL_ERROR\x10\x02\x12\x15\n" +
	"\x11SYSTEM_USER_ERROR\x10d\x12\x19\n" +
	"\x15SYSTEM_USER_NOT_FOUND\x10e\x12\x1b\n" +
	"\x11SYSTEM_AUTH_ERROR\x10f\x1a\x04\xa8E\x91\x03\x12\x16\n" +
	"\x11SYSTEM_ROLE_ERROR\x10\xc8\x01\x12\x16\n" +
	"\x11SYSTEM_MENU_ERROR\x10\xac\x02\x12\x1c\n" +
	"\x17SYSTEM_PERMISSION_ERROR\x10\x90\x03\x12\x16\n" +
	"\x11SYSTEM_DICT_ERROR\x10\xf4\x03\x12\x16\n" +
	"\x11SYSTEM_DEPT_ERROR\x10\xd8\x04\x12\x16\n" +
	"\x11SYSTEM_POST_ERROR\x10\xbc\x05\x12\x1e\n" +
	"\x19SYSTEM_OSS_CONFIG_INVALID\x10\x84\a\x12!\n" +
	"\x1cSYSTEM_OSS_CONFIG_INCOMPLETE\x10\x85\a\x12#\n" +
	"\x1eSYSTEM_OSS_SERVICE_UNAVAILABLE\x10\x86\a\x12\"\n" +
	"\x1dSYSTEM_OSS_PROVIDER_NOT_FOUND\x10\x87\a\x1a\x04\xa0E\xf4\x03B\x1dZ\x1bspark/api/common/v1;v1b\x06proto3"

var (
	file_common_v1_error_proto_rawDescOnce sync.Once
	file_common_v1_error_proto_rawDescData []byte
)

func file_common_v1_error_proto_rawDescGZIP() []byte {
	file_common_v1_error_proto_rawDescOnce.Do(func() {
		file_common_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_error_proto_rawDesc), len(file_common_v1_error_proto_rawDesc)))
	})
	return file_common_v1_error_proto_rawDescData
}

var file_common_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.kratos.v1.ErrorReason
}
var file_common_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_error_proto_init() }
func file_common_v1_error_proto_init() {
	if File_common_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_error_proto_rawDesc), len(file_common_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_error_proto_goTypes,
		DependencyIndexes: file_common_v1_error_proto_depIdxs,
		EnumInfos:         file_common_v1_error_proto_enumTypes,
	}.Build()
	File_common_v1_error_proto = out.File
	file_common_v1_error_proto_goTypes = nil
	file_common_v1_error_proto_depIdxs = nil
}
